### ISSUE TITLE
gitlab-ci运行出错

### ISSUE THREAD

**Issue by wengych** [surgioproject/surgio#128]
.gitlab-ci.yml
``` .yml
image: node:14-stretch

before_script:
  - 'npm install --production'

stages:
  - build

build:
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - dist/
  only:
    - web # 能够在网页上触发
    - triggers # 能够通过 API 触发
    - schedules # 能够定时触发
  script:
    - npm run update
```

CI Job log
```
$ npm run update
> my-rule-store@0.1.0 update /builds/wengych/wengych.gitlab.io
> surgio generate
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'source-map-support/register'
Require stack:
- /builds/wengych/wengych.gitlab.io/node_modules/surgio/build/index.js
- /builds/wengych/wengych.gitlab.io/node_modules/surgio/bin/surgio.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/builds/wengych/wengych.gitlab.io/node_modules/surgio/build/index.js:26:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/builds/wengych/wengych.gitlab.io/node_modules/surgio/build/index.js',
    '/builds/wengych/wengych.gitlab.io/node_modules/surgio/bin/surgio.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-rule-store@0.1.0 update: `surgio generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-rule-store@0.1.0 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-17T11_59_00_563Z-debug.log
```

**Comment by geekdada** [comment]
升级一下Surgio，新版已经修复这个问题
