### ISSUE TITLE
多个过滤器合并

### ISSUE THREAD

**Issue by zsbai** [surgioproject/surgio#149]
customFilters: {
    hongkong_with_no_IPLC: utils.mergeFilters([utils.noIPLC, utils.hkFilter], true),
    IPLC: nodeConfig => nodeConfig.nodeName.includes('IPLC', 'IEPL'),
    noIPLC: utils.discardKeywords(['IPLC','IEPL']),
    
  },
我想筛选出香港，并且没有IPLC的节点，这样写报错：
⚠️  发生错误
⚠️  TypeError: Cannot read property 'hasOwnProperty' of undefined
⚠️  版本号: 2.9.0
⚠️  常见问题: http://url.royli.dev/7EMxu
⚠️  加入交流群汇报问题 https://t.me/surgiotg

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at /Users/bailu/work/my-rule-store/node_modules/surgio/lib/utils/filter.ts:74:16
    at Array.forEach (<anonymous>)
    at Object.mergeFilters (/Users/bailu/work/my-rule-store/node_modules/surgio/lib/utils/filter.ts:73:11)
    at Object.<anonymous> (/Users/bailu/work/my-rule-store/surgio.conf.js:50:34)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loadConfig (/Users/bailu/work/my-rule-store/node_modules/surgio/lib/utils/config.ts:28:34)
    at GenerateCommand.run (/Users/bailu/work/my-rule-store/node_modules/surgio/lib/command/generate.ts:52:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

@surgio/gateway: 1.3.0
surgio: 2.9.0 (/Users/bailu/work/my-rule-store/node_modules/surgio)
node: 12.18.3 (/usr/local/bin/node)
yarn: 1.22.10
npm: 7.13.0
npx: 7.13.0

然后我尝试这样写：
customFilters: {
    hongkong_with_no_IPLC: utils.mergeFilters([utils.customFilters.noIPLC, utils.hkFilter], true),
    IPLC: nodeConfig => nodeConfig.nodeName.includes('IPLC', 'IEPL'),
    noIPLC: utils.discardKeywords(['IPLC','IEPL']),
  },
依旧报错：
⚠️  发生错误
⚠️  TypeError: Cannot read property 'noIPLC' of undefined
⚠️  版本号: 2.9.0
⚠️  常见问题: http://url.royli.dev/7EMxu
⚠️  加入交流群汇报问题 https://t.me/surgiotg

TypeError: Cannot read property 'IPLC' of undefined
    at Object.<anonymous> (/Users/bailu/work/my-rule-store/surgio.conf.js:50:68)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loadConfig (/Users/bailu/work/my-rule-store/node_modules/surgio/lib/utils/config.ts:28:34)
    at GenerateCommand.run (/Users/bailu/work/my-rule-store/node_modules/surgio/lib/command/generate.ts:52:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

合并过滤器是没办法把自定义过滤器合并进去？还是我的方法不对？文档翻遍了，也没找到解决办法...

**Comment by honjow** [comment]
有点没太理解你到底要干嘛，发出来的信息有帮助的也不多
不存在 `utils.customFilters.noIPLC` 的写法
要在`customFilters`里的filter不能互相引用。你要引用自定FIlter的话先用`const`定义一下


```
const _ noIPLC = utils.discardKeywords(['IPLC','IEPL'])

customFilters: {
hongkong_with_no_IPLC: utils.mergeFilters([_noIPLC, utils.hkFilter], true),
},

```

**Comment by zsbai** [comment]
已解决，感谢

**Comment by fbigun** [comment]
> 已解决，感谢

按楼上方法处理的吗？

**Comment by zsbai** [comment]
> > 已解决，感谢
> 
> 
> 
> 按楼上方法处理的吗？
> 
> 
> 
> @zsbai

对的
