### ISSUE TITLE
程序化配置文件

### ISSUE THREAD

**Issue by liblaf** [surgioproject/surgio#279]
希望能够将 `surgio` 作为第三方库使用, 例如:

```typescript
import { defineClashProvider } from "surgio";
import { getProvider } from "surgio/provider";

const provider = await getProvider(
  "NAME",
  defineClashProvider({ url: "https://example.com" }),
);
console.log(provider.getNodeList());
```

但得到了如下错误:

```txt
50 | };
51 | exports.loadConfig = loadConfig;
52 | const getConfig = () => {
53 |     // istanbul ignore next
54 |     if (!finalConfig) {
55 |         throw new Error('请先调用 loadConfig 方法');
                   ^
error: 请先调用 loadConfig 方法
      at getConfig (***/node_modules/surgio/build/config.js:55:15)
      at new Provider (***/node_modules/surgio/build/provider/Provider.js:59:26)
      at new ClashProvider (***/node_modules/surgio/build/provider/ClashProvider.js:25:9)
      at ***/node_modules/surgio/build/provider/index.js:44:20
      at getProvider (***/node_modules/surgio/build/provider/index.js:26:28)
      at ***/hello.ts:4:24

Bun v1.1.21 (Linux x64)
```

https://github.com/surgioproject/surgio/blob/7bc53d4e3531b2eeced3f9f91e3ce9320b25523c/src/config.ts#L20-L61

注意到 [`loadConfig()`](https://github.com/surgioproject/surgio/blob/7bc53d4e3531b2eeced3f9f91e3ce9320b25523c/src/config.ts#L20-L61) 需要从文件系统中读取 `surgio.conf.js` 并保存在 `finalConfig` 中. 是否可以允许程序化设置 `finalConfig` 而无需 `surgio.conf.js` 文件?

**Comment by geekdada** [comment]
请问这么做是要实现什么功能？

**Comment by liblaf** [comment]
> 请问这么做是要实现什么功能？

@geekdada 我希望在 serverless (例如 cf worker) 上部署代理规则生成器, 我希望能够复用 surgio 部分代码.

**Comment by imbytecat** [comment]
同样有这个需求，写死 `surgio.conf.js` 非常不灵活，而且我也使用 TypeScript
